In [ ]:
import numpy as np
import pandas as pd

movies=pd.read_csv('imdb-top-1000.csv')

In [ ]:
movies

In [9]:
movies.head(1)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0

Group By:
Used to group columns on the basis of category and numeric values

In [17]:
#Applying builtin aggergate functions on groupby objects
genre=movies.groupby('Genre')
genre.sum(numeric_only=True)

           Runtime  IMDB_Rating  No_of_Votes         Gross  Metascore
Genre
Action       22196       1367.3     72282412  3.263226e+10    10499.0
Adventure     9656        571.5     22576163  9.496922e+09     5020.0
Animation     8166        650.3     21978630  1.463147e+10     6082.0
Biography    11970        698.6     24006844  8.276358e+09     6023.0
Comedy       17380       1224.7     27620327  1.566387e+10     9840.0
Crime        13524        857.8     33533615  8.452632e+09     6706.0
Drama        36049       2299.7     61367304  3.540997e+10    19208.0
Family         215         15.6       551221  4.391106e+08      158.0
Fantasy        170         16.0       146222  7.827267e+08        0.0
Film-Noir      312         23.9       367215  1.259105e+08      287.0
Horror        1123         87.0      3742556  1.034649e+09      880.0
Mystery       1429         95.7      4203004  1.256417e+09      633.0
Thriller       108          7.8        27733  1.755074e+07       81.0
Western        593         33.4      1289665  5.822151e+07      313.0

In [19]:
#Find the top 3 genres by total earning
movies.groupby('Genre')['Gross'].sum().sort_values(ascending=False).head(3)

Genre
Drama     3.540997e+10
Action    3.263226e+10
Comedy    1.566387e+10
Name: Gross, dtype: float64

In [22]:
#find the genre with highest avg imdb rating
movies.groupby('Genre')['IMDB_Rating'].mean().sort_values(ascending=False).head(1)

Genre
Western    8.35
Name: IMDB_Rating, dtype: float64

In [23]:
movies

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
996,Giant,1956,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0
997,From Here to Eternity,1953,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0
998,Lifeboat,1944,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
999,The 39 Steps,1935,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0

In [26]:
#find director with most popularity
movies.groupby('Director')['No_of_Votes'].sum().sort_values(ascending=False).head(1)

Director
Christopher Nolan    11578345
Name: No_of_Votes, dtype: int64

In [43]:
# find number of movies done by each actor
movies.groupby('Star1')['Series_Title'].count().sort_values(ascending=False)
# movies['Star1'].value_counts()

Star1
Tom Hanks               12
Robert De Niro          11
Clint Eastwood          10
Al Pacino               10
Humphrey Bogart          9
                        ..
Zbigniew Zamachowski     1
Zooey Deschanel          1
Çetin Tekindor           1
Éric Toledano            1
Aaron Taylor-Johnson     1
Name: Series_Title, Length: 660, dtype: int64

In [59]:
# Group By Attributes and Method:
# find total number of groups -> Length
len(genre)

# find items in each group -> Size
genre.size()

# first()/last()->nth item
genre.first()
genre.last()
genre.nth(6).set_index('Genre')

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,Star Wars: Episode V - The Empire Strikes Back,1980,124,8.7,Irvin Kershner,Mark Hamill,1159315,290475067.0,82.0
Crime,Se7en,1995,127,8.6,David Fincher,Morgan Freeman,1445096,100125643.0,65.0
Drama,It's a Wonderful Life,1946,130,8.6,Frank Capra,James Stewart,405801,82385199.0,89.0
Animation,WALL·E,2008,98,8.4,Andrew Stanton,Ben Burtt,999790,223808164.0,95.0
Comedy,The Great Dictator,1940,125,8.4,Charles Chaplin,Charles Chaplin,203150,288475.0,NaN
Biography,Braveheart,1995,178,8.3,Mel Gibson,Mel Gibson,959181,75600000.0,68.0
Adventure,North by Northwest,1959,136,8.3,Alfred Hitchcock,Cary Grant,299198,13275000.0,98.0
Mystery,Sleuth,1972,138,8.0,Joseph L. Mankiewicz,Laurence Olivier,44748,4081254.0,NaN
Horror,Get Out,2017,104,7.7,Jordan Peele,Daniel Kaluuya,492851,176040665.0,85.0

In [ ]:
#get_group -> vs filtering: to fetch a particulat group
genre.get_group('Animation')

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
23,Sen to Chihiro no kamikakushi,2001,125,Animation,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
43,The Lion King,1994,88,Animation,8.5,Roger Allers,Rob Minkoff,942045,422783777.0,88.0
46,Hotaru no haka,1988,89,Animation,8.5,Isao Takahata,Tsutomu Tatsumi,235231,150734678.0,94.0
56,Kimi no na wa.,2016,106,Animation,8.4,Makoto Shinkai,Ryûnosuke Kamiki,194838,5017246.0,79.0
58,Spider-Man: Into the Spider-Verse,2018,117,Animation,8.4,Bob Persichetti,Peter Ramsey,375110,190241310.0,87.0
...,...,...,...,...,...,...,...,...,...,...
956,Mulan,1998,88,Animation,7.6,Tony Bancroft,Barry Cook,256906,120620254.0,71.0
971,Omohide poro poro,1991,118,Animation,7.6,Isao Takahata,Miki Imai,27071,453243.0,90.0
976,The Little Mermaid,1989,83,Animation,7.6,Ron Clements,John Musker,237696,111543479.0,88.0
986,Watership Down,1978,91,Animation,7.6,Martin Rosen,John Hubley,33656,232841485.0,64.0
992,The Jungle Book,1967,78,Animation,7.6,Wolfgang Reitherman,Phil Harris,166409,141843612.0,65.0

In [62]:
#Groups:
genre.groups

{'Action': [2, 5, 8, 10, 13, 14, 16, 29, 30, 31, 39, 42, 44, 55, 57, 59, 60, 63, 68, 72, 106, 109, 129, 130, 134, 140, 142, 144, 152, 155, 160, 161, 166, 168, 171, 172, 177, 181, 194, 201, 202, 216, 217, 223, 224, 236, 241, 262, 275, 294, 308, 320, 325, 326, 331, 337, 339, 340, 343, 345, 348, 351, 353, 356, 357, 362, 368, 369, 375, 376, 390, 410, 431, 436, 473, 477, 479, 482, 488, 493, 496, 502, 507, 511, 532, 535, 540, 543, 564, 569, 570, 573, 577, 582, 583, 602, 605, 608, 615, 623, ...], 'Adventure': [21, 47, 93, 110, 114, 116, 118, 137, 178, 179, 191, 193, 209, 226, 231, 247, 267, 273, 281, 300, 301, 304, 306, 323, 329, 361, 366, 377, 402, 406, 415, 426, 458, 470, 497, 498, 506, 513, 514, 537, 549, 552, 553, 566, 576, 604, 609, 618, 638, 647, 675, 681, 686, 692, 711, 713, 739, 755, 781, 797, 798, 851, 873, 884, 912, 919, 947, 957, 964, 966, 984, 991], 'Animation': [23, 43, 46, 56, 58, 61, 66, 70, 101, 135, 146, 151, 158, 170, 197, 205, 211, 213, 219, 229, 230, 242, 245, 246, 270, 330, 332, 358, 367, 378, 386, 389, 394, 395, 399, 401, 405, 409, 469, 499, 510, 516, 518, 522, 578, 586, 592, 595, 596, 599, 633, 640, 643, 651, 665, 672, 694, 728, 740, 741, 744, 756, 758, 761, 771, 783, 796, 799, 822, 828, 843, 875, 891, 892, 902, 906, 920, 956, 971, 976, 986, 992], 'Biography': [7, 15, 18, 35, 38, 54, 102, 107, 131, 139, 147, 157, 159, 173, 176, 212, 215, 218, 228, 235, 243, 263, 276, 282, 290, 298, 317, 328, 338, 342, 346, 359, 360, 365, 372, 373, 385, 411, 416, 418, 424, 429, 484, 525, 536, 542, 545, 575, 579, 587, 600, 606, 614, 622, 632, 635, 644, 649, 650, 657, 671, 673, 684, 729, 748, 753, 757, 759, 766, 770, 779, 809, 810, 815, 820, 831, 849, 858, 877, 882, 897, 910, 915, 923, 940, 949, 952, 987], 'Comedy': [19, 26, 51, 52, 64, 78, 83, 95, 96, 112, 117, 120, 127, 128, 132, 153, 169, 183, 192, 204, 207, 208, 214, 221, 233, 238, 240, 250, 251, 252, 256, 261, 266, 277, 284, 311, 313, 316, 318, 322, 327, 374, 379, 381, 392, 396, 403, 413, 414, 417, 427, 435, 445, 446, 449, 455, 459, 460, 463, 464, 466, 471, 472, 475, 481, 490, 494, 500, 503, 509, 526, 528, 530, 531, 533, 538, 539, 541, 547, 557, 558, 562, 563, 565, 574, 591, 593, 594, 598, 613, 626, 630, 660, 662, 667, 679, 680, 683, 687, 701, ...], 'Crime': [1, 3, 4, 6, 22, 25, 27, 28, 33, 37, 41, 71, 77, 79, 86, 87, 103, 108, 111, 113, 123, 125, 133, 136, 162, 163, 164, 165, 180, 186, 187, 189, 198, 222, 232, 239, 255, 257, 287, 288, 299, 305, 335, 363, 364, 380, 384, 397, 437, 438, 441, 442, 444, 450, 451, 465, 474, 480, 485, 487, 505, 512, 519, 520, 523, 527, 546, 556, 560, 584, 597, 603, 607, 611, 621, 639, 653, 664, 669, 676, 695, 708, 723, 762, 763, 767, 775, 791, 795, 802, 811, 823, 827, 833, 885, 895, 921, 922, 926, 938, ...], 'Drama': [0, 9, 11, 17, 20, 24, 32, 34, 36, 40, 45, 50, 53, 62, 65, 67, 73, 74, 76, 80, 82, 84, 85, 88, 89, 90, 91, 92, 94, 97, 98, 99, 100, 104, 105, 121, 122, 124, 126, 138, 141, 143, 148, 149, 150, 154, 156, 167, 174, 175, 182, 184, 185, 188, 190, 195, 196, 199, 200, 203, 206, 210, 225, 227, 234, 237, 244, 248, 249, 253, 254, 258, 259, 260, 264, 265, 268, 269, 272, 274, 278, 279, 280, 283, 285, 286, 289, 291, 292, 293, 295, 296, 297, 302, 303, 307, 310, 312, 314, 315, ...], 'Family': [688, 698], 'Fantasy': [321, 568], 'Film-Noir': [309, 456, 712], 'Horror': [49, 75, 271, 419, 544, 707, 724, 844, 876, 932, 948], 'Mystery': [69, 81, 119, 145, 220, 393, 420, 714, 829, 899, 959, 961], 'Thriller': [700], 'Western': [12, 48, 115, 691]}

In [66]:
# describe
# sample
# nunique
genre.describe()
genre.sample(2,replace=True)
genre.nunique()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,172,61,78,15,123,121,172,172,50
Adventure,72,49,58,10,59,59,72,72,33
Animation,82,35,41,11,51,77,82,82,29
Biography,88,44,56,13,76,72,88,88,40
Comedy,155,72,70,11,113,133,155,155,44
Crime,106,56,65,14,86,85,107,107,39
Drama,289,83,95,14,211,250,288,287,52
Family,2,2,2,1,2,2,2,2,2
Fantasy,2,2,2,2,2,2,2,2,0
Film-Noir,3,3,3,3,3,3,3,3,3
Horror,11,11,10,8,10,11,11,11,9
Mystery,12,11,10,8,10,11,12,12,7
Thriller,1,1,1,1,1,1,1,1,1
Western,4,4,4,4,2,2,4,4,4

In [68]:
# agg method
#passing dict
genre.agg({
    'Runtime':'mean',
    'IMDB_Rating':'mean',
    'No_of_Votes':'sum',
    'Gross':'sum',
    'Metascore':'min'
})

              Runtime  IMDB_Rating  No_of_Votes         Gross  Metascore
Genre
Action     129.046512     7.949419     72282412  3.263226e+10       33.0
Adventure  134.111111     7.937500     22576163  9.496922e+09       41.0
Animation   99.585366     7.930488     21978630  1.463147e+10       61.0
Biography  136.022727     7.938636     24006844  8.276358e+09       48.0
Comedy     112.129032     7.901290     27620327  1.566387e+10       45.0
Crime      126.392523     8.016822     33533615  8.452632e+09       47.0
Drama      124.737024     7.957439     61367304  3.540997e+10       28.0
Family     107.500000     7.800000       551221  4.391106e+08       67.0
Fantasy     85.000000     8.000000       146222  7.827267e+08        NaN
Film-Noir  104.000000     7.966667       367215  1.259105e+08       94.0
Horror     102.090909     7.909091      3742556  1.034649e+09       46.0
Mystery    119.083333     7.975000      4203004  1.256417e+09       52.0
Thriller   108.000000     7.800000        27733  1.755074e+07       81.0
Western    148.250000     8.350000      1289665  5.822151e+07       69.0

In [72]:
# passing list
genre[['Runtime','IMDB_Rating']].agg(['mean','max','min'])

              Runtime           IMDB_Rating
                 mean  max  min        mean  max  min
Genre
Action     129.046512  321   45    7.949419  9.0  7.6
Adventure  134.111111  228   88    7.937500  8.6  7.6
Animation   99.585366  137   71    7.930488  8.6  7.6
Biography  136.022727  209   93    7.938636  8.9  7.6
Comedy     112.129032  188   68    7.901290  8.6  7.6
Crime      126.392523  229   80    8.016822  9.2  7.6
Drama      124.737024  242   64    7.957439  9.3  7.6
Family     107.500000  115  100    7.800000  7.8  7.8
Fantasy     85.000000   94   76    8.000000  8.1  7.9
Film-Noir  104.000000  108  100    7.966667  8.1  7.8
Horror     102.090909  122   71    7.909091  8.5  7.6
Mystery    119.083333  138   96    7.975000  8.4  7.6
Thriller   108.000000  108  108    7.800000  7.8  7.8
Western    148.250000  165  132    8.350000  8.8  7.8

In [71]:
#Adding both the syntax
genre.agg({
    'Runtime':['mean','sum'],
    'IMDB_Rating':['mean','sum'],
    'No_of_Votes':['sum','mean'],
    'Gross':'sum',
    'Metascore':'min'
})

              Runtime        IMDB_Rating         No_of_Votes                 \
                 mean    sum        mean     sum         sum           mean
Genre
Action     129.046512  22196    7.949419  1367.3    72282412  420246.581395
Adventure  134.111111   9656    7.937500   571.5    22576163  313557.819444
Animation   99.585366   8166    7.930488   650.3    21978630  268032.073171
Biography  136.022727  11970    7.938636   698.6    24006844  272805.045455
Comedy     112.129032  17380    7.901290  1224.7    27620327  178195.658065
Crime      126.392523  13524    8.016822   857.8    33533615  313398.271028
Drama      124.737024  36049    7.957439  2299.7    61367304  212343.612457
Family     107.500000    215    7.800000    15.6      551221  275610.500000
Fantasy     85.000000    170    8.000000    16.0      146222   73111.000000
Film-Noir  104.000000    312    7.966667    23.9      367215  122405.000000
Horror     102.090909   1123    7.909091    87.0     3742556  340232.363636
Mystery    119.083333   1429    7.975000    95.7     4203004  350250.333333
Thriller   108.000000    108    7.800000     7.8       27733   27733.000000
Western    148.250000    593    8.350000    33.4     1289665  322416.250000

                  Gross Metascore
                    sum       min
Genre
Action     3.263226e+10      33.0
Adventure  9.496922e+09      41.0
Animation  1.463147e+10      61.0
Biography  8.276358e+09      48.0
Comedy     1.566387e+10      45.0
Crime      8.452632e+09      47.0
Drama      3.540997e+10      28.0
Family     4.391106e+08      67.0
Fantasy    7.827267e+08       NaN
Film-Noir  1.259105e+08      94.0
Horror     1.034649e+09      46.0
Mystery    1.256417e+09      52.0
Thriller   1.755074e+07      81.0
Western    5.822151e+07      69.0

In [86]:
# find the highest rated movie in each genre
# looping on groups


highest_rated_movies=[]
for groups,data in genre:
    top_movie=data[data['IMDB_Rating']==data['IMDB_Rating'].max()]
    highest_rated_movies.append(top_movie)

df=pd.concat(highest_rated_movies)
df

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
21,Interstellar,2014,169,Adventure,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
23,Sen to Chihiro no kamikakushi,2001,125,Animation,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
7,Schindler's List,1993,195,Biography,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
19,Gisaengchung,2019,132,Comedy,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
26,La vita è bella,1997,116,Comedy,8.6,Roberto Benigni,Roberto Benigni,623629,57598247.0,59.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
688,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
698,Willy Wonka & the Chocolate Factory,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
309,The Third Man,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
49,Psycho,1960,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
69,Memento,2000,113,Mystery,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
81,Rear Window,1954,112,Mystery,8.4,Alfred Hitchcock,James Stewart,444074,36764313.0,100.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
12,"Il buono, il brutto, il cattivo",1966,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

In [89]:
# split (apply) combine
# apply -> builtin function

# find the number of movies starting with A in each group

def movies_count(group):
    return group['Series_Title'].str.startswith('A').sum()

genre.apply(movies_count).sort_values(ascending=False)

Genre
Drama        21
Comedy       14
Action       10
Biography     9
Crime         4
Adventure     2
Animation     2
Horror        1
Fantasy       0
Family        0
Film-Noir     0
Mystery       0
Thriller      0
Western       0
dtype: int64

In [94]:
# find ranking of each movie in the group according to the IMDB rating

def ranking(group):
     group['Rank']=group['IMDB_Rating'].rank(ascending=False)
     return group

genre.apply(ranking).reset_index()

,Genre,level_1,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore,Rank
0,Action,2,The Dark Knight,2008,152,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0,1.0
1,Action,5,The Lord of the Rings: The Return of the King,2003,201,8.9,Peter Jackson,Elijah Wood,1642758,377845905.0,94.0,2.0
2,Action,8,Inception,2010,148,8.8,Christopher Nolan,Leonardo DiCaprio,2067042,292576195.0,74.0,3.5
3,Action,10,The Lord of the Rings: The Fellowship of the Ring,2001,178,8.8,Peter Jackson,Elijah Wood,1661481,315544750.0,92.0,3.5
4,Action,13,The Lord of the Rings: The Two Towers,2002,179,8.7,Peter Jackson,Elijah Wood,1485555,342551365.0,87.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,Thriller,700,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0,1.0
996,Western,12,"Il buono, il brutto, il cattivo",1966,161,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0,1.0
997,Western,48,Once Upon a Time in the West,1968,165,8.5,Sergio Leone,Henry Fonda,302844,5321508.0,80.0,2.0
998,Western,115,Per qualche dollaro in più,1965,132,8.3,Sergio Leone,Clint Eastwood,232772,15000000.0,74.0,3.0
999,Western,691,The Outlaw Josey Wales,1976,135,7.8,Clint Eastwood,Clint Eastwood,65659,31800000.0,69.0,4.0

In [96]:
# find normalized IMDB Ranking for each group
def normalized_rating(group):
    group['Normalized_Rating']=(group['IMDB_Rating']-group['IMDB_Rating'].min())/(group['IMDB_Rating'].max()-group['IMDB_Rating'].min())
    return group

genre.apply(normalized_rating).reset_index()

,Genre,level_1,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore,Normalized_Rating
0,Action,2,The Dark Knight,2008,152,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0,1.000000
1,Action,5,The Lord of the Rings: The Return of the King,2003,201,8.9,Peter Jackson,Elijah Wood,1642758,377845905.0,94.0,0.928571
2,Action,8,Inception,2010,148,8.8,Christopher Nolan,Leonardo DiCaprio,2067042,292576195.0,74.0,0.857143
3,Action,10,The Lord of the Rings: The Fellowship of the Ring,2001,178,8.8,Peter Jackson,Elijah Wood,1661481,315544750.0,92.0,0.857143
4,Action,13,The Lord of the Rings: The Two Towers,2002,179,8.7,Peter Jackson,Elijah Wood,1485555,342551365.0,87.0,0.785714
...,...,...,...,...,...,...,...,...,...,...,...,...
995,Thriller,700,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0,NaN
996,Western,12,"Il buono, il brutto, il cattivo",1966,161,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0,1.000000
997,Western,48,Once Upon a Time in the West,1968,165,8.5,Sergio Leone,Henry Fonda,302844,5321508.0,80.0,0.700000
998,Western,115,Per qualche dollaro in più,1965,132,8.3,Sergio Leone,Clint Eastwood,232772,15000000.0,74.0,0.500000
999,Western,691,The Outlaw Josey Wales,1976,135,7.8,Clint Eastwood,Clint Eastwood,65659,31800000.0,69.0,0.000000

In [102]:
# groupby on multiple columns
duo=movies.groupby(['Director','Star1'])
duo.size().sort_values(ascending=False)
duo.get_group(('Akira Kurosawa','Toshirô Mifune'))

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
31,Shichinin no samurai,1954,207,Action,8.6,Akira Kurosawa,Toshirô Mifune,315744,269061.0,98.0
77,Tengoku to jigoku,1963,143,Crime,8.4,Akira Kurosawa,Toshirô Mifune,34357,620361655.0,NaN
181,Yôjinbô,1961,110,Action,8.2,Akira Kurosawa,Toshirô Mifune,111244,474518350.0,NaN
189,Rashômon,1950,88,Crime,8.2,Akira Kurosawa,Toshirô Mifune,152572,96568.0,98.0
294,Sanjuro,1962,96,Action,8.1,Akira Kurosawa,Toshirô Mifune,33044,848120995.0,NaN
301,Kakushi-toride no san-akunin,1958,139,Adventure,8.1,Akira Kurosawa,Toshirô Mifune,34797,443906080.0,NaN
303,Kumonosu-jô,1957,110,Drama,8.1,Akira Kurosawa,Toshirô Mifune,46678,612604239.0,NaN

In [105]:
# find the most earning actor->director combo
duo['Gross'].sum().sort_values(ascending=False).head(1)

Director        Star1
Akira Kurosawa  Toshirô Mifune    2.999877e+09
Name: Gross, dtype: float64

In [115]:
# find the best (in terms of metascore avg) actor-genre combo
actor_genre=movies.groupby(['Star1','Genre'])
actor_genre['Metascore'].mean().reset_index().sort_values('Metascore',ascending=False).head(7)

               Star1      Genre  Metascore
606    Peter O'Toole  Adventure      100.0
590     Orson Welles      Drama      100.0
77       Bertil Guve      Drama      100.0
230   Ellar Coltrane      Drama      100.0
329  Humphrey Bogart      Drama      100.0
127       Cary Grant      Drama      100.0
360    James Stewart    Mystery      100.0