In [4]:
import pandas as pd
import numpy as np

In [30]:
url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv"
titanic_df = pd.read_csv(url)

In [3]:
titanic_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

Q-1: Using groupby make groups using the "Pclass" column and find out the average age and total number of missing values in the "Age" column for every group

In [ ]:
pclass=titanic_df.groupby('Pclass')

pclass.agg({
    'Age':['mean',lambda x:x.isnull().sum()]
})

pclass.agg(
    Average_Age=('Age','mean'),
    Missing_Ages=('Age',lambda x:x.isnull().sum())
)

        Average_Age  Missing_Ages
Pclass
1         38.233441            30
2         29.877630            11
3         25.140620           136

Q-2: Using groupby make groups using the "Pclass" column and fill every group's "Embarked" column's missing values with the mode value of that group. After that, print every group's "Embarked" column's value counts in ascending order.

In [34]:
titanic_df['Embarked']=pclass['Embarked'].apply(lambda x:x.fillna(x.mode()[0])).reset_index(level=0,drop=True)
pclass['Embarked'].value_counts().sort_values()

Pclass  Embarked
1       Q             2
2       Q             3
        C            17
3       C            66
        Q            72
1       C            85
        S           129
2       S           164
3       S           353
Name: count, dtype: int64

Q-3: Make groups based on "Embarked" column. And for each of this embarked group, make another group based on "Pclass" and find out the average fare (round off up to 2 decimal places) for each "Pclass" for each group of "Embarked".
Sample Output:

{'C': {1: 105, 2: 25, 3: 11},
 'Q': {1: 90, 2: 12, 3: 11},
 'S': {1: 70, 2: 20, 3: 15}}

In [43]:
embarked=titanic_df.groupby(['Embarked','Pclass'])
embarked['Fare'].mean().round(0).astype(int).unstack().to_dict(orient='index')

{'C': {1: 105, 2: 25, 3: 11},
 'Q': {1: 90, 2: 12, 3: 11},
 'S': {1: 71, 2: 20, 3: 15}}

In [44]:

fifa_df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv")

In [45]:
fifa_df

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,...,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
0,1,1,Qatar,Ecuador,A,0,40,0,0,0,...,15,3,453,387,10,5,1,19,0,0
1,2,1,Ecuador,Qatar,A,2,46,2,0,1,...,15,4,484,419,26,10,3,17,1,3
2,3,2,England,Iran,B,6,69,6,0,6,...,9,2,810,733,29,9,8,16,0,3
3,4,2,Iran,England,B,2,20,2,0,1,...,14,2,232,156,11,3,0,10,1,0
4,5,3,Senegal,Netherlands,A,0,39,0,0,0,...,13,2,391,326,22,8,6,14,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,124,62,Morocco,Fram,F,0,55,0,0,0,...,11,3,583,518,22,1,3,15,0,0
124,125,63,Croatia,Morocco,F,2,45,2,0,2,...,13,2,491,430,21,3,6,13,0,3
125,126,63,Morocco,Croatia,F,1,45,1,0,0,...,11,2,494,428,20,5,3,15,0,0
126,127,64,Argentina,France,C,3,46,3,0,1,...,26,4,648,544,20,4,6,22,5,3
127,128,64,France,Argentina,D,3,40,3,0,1,...,19,4,516,419,24,3,5,28,4,0

Q-4: Perform groupby based on the "Team" column and then perform Z Normalization on top of the below columns of each group:
Passes
Passes Completed
Attempted Line Breaks
Completed Line Breaks
You have to make a python function named z_normalization which takes two arguments:

group: Every group that you have created
cols_to_perform: This parameter takes a list of columns on which you have to perform the Z-Normalization.
For this problem, you have to use th apply() method.

Z − Normalization=Xi−μstd 

After that find out the below values for each group:

minimum "Passess"
maximum "Passess"
minimum "Yellow Cards"
maximum "Yellow cards"
average "Yellow Cards"
maximum "Attempted Line Breaks"
minimum "Attempted Line Breaks"
standardard deviation of "Attempted Line Breaks"
average Possession

In [61]:
def z_normalization(group,column_list):
    mean_val=group[column_list].mean()
    std=group[column_list].std()

    group[column_list]=(group[column_list]-mean_val)/std
    return group

column_list=['Passes','Passes Completed','Attempted Line Breaks','Completed Line Breaks']
teams=fifa_df.groupby('Team')

normalized_df=teams.apply(z_normalization,column_list=column_list)
normalized_teams=normalized_df.groupby('Team')

normalized_teams.agg({
    'Passes':['min','max'],
    'Yellow Cards':['min','max','mean'],
    'Attempted Line Breaks':['max','min','std'],
    'Possession (%)':'mean'
})

                  Passes           Yellow Cards                \
                     min       max          min max      mean
Team
Argentina      -1.510257  1.685214            0   8  2.285714
Australia      -1.114789  0.932782            0   3  1.750000
Belgium        -1.082696  0.888950            1   3  1.666667
Brazil         -0.928871  1.609122            0   3  1.200000
Cameroon       -0.875605  1.089713            1   5  2.666667
Canada         -1.120897  0.800641            2   4  2.666667
Costa Rica     -1.013178  0.986279            1   3  2.000000
Croatia        -1.441280  1.093005            0   2  1.142857
Denmark        -1.046208  0.946290            1   2  1.666667
Ecuador        -0.883020  1.085876            0   2  1.000000
England        -0.877731  1.705844            0   1  0.200000
France         -1.219077  1.571019            0   3  1.142857
Germany        -1.131449  0.765392            0   3  1.000000
Ghana          -1.045786  0.946861            2   4  2.666667
Iran           -0.820695  1.113800            2   3  2.333333
Japan          -1.001479  0.979825            0   3  1.500000
Korea Republic -1.157924  0.877868            1   2  1.500000
Mexico         -0.918398  1.065342            1   4  2.333333
Morocco        -1.384362  1.662218            0   3  1.285714
Netherlands    -1.051749  1.428668            0   4  1.800000
Poland         -0.694755  1.483035            1   3  1.750000
Portugal       -1.646177  1.035658            0   3  1.200000
Qatar          -1.147558  0.684833            0   4  2.333333
Saudi Arabia   -0.667896  1.149691            2   6  4.666667
Senegal        -1.214144  1.235077            1   3  1.750000
Serbia         -1.089807  0.875419            2   7  4.000000
Spain          -1.498758  0.554601            0   1  0.500000
Switzerland    -1.469082  0.754945            1   4  2.250000
Tunisia        -0.965692  1.031097            1   3  1.666667
United States  -1.136338  0.860862            0   4  1.250000
Uruguay        -0.931702  1.056570            1   3  2.000000
Wales          -0.971590  1.026174            1   2  1.666667

               Attempted Line Breaks                Possession (%)
                                 max       min  std           mean
Team
Argentina                   1.757406 -1.027917  1.0      49.285714
Australia                   0.961409 -1.187623  1.0      31.250000
Belgium                     1.109400 -0.832050  1.0      49.000000
Brazil                      1.085013 -1.627519  1.0      50.400000
Cameroon                    0.788942 -1.124661  1.0      38.333333
Canada                      0.865260 -1.094819  1.0      44.333333
Costa Rica                  0.590132 -1.154606  1.0      27.333333
Croatia                     1.187420 -1.785063  1.0      47.428571
Denmark                     1.000000 -1.000000  1.0      51.333333
Ecuador                     1.019020 -0.979827  1.0      42.666667
England                     1.354603 -1.172641  1.0      57.200000
France                      1.147789 -1.327966  1.0      44.857143
Germany                     1.036065 -0.959538  1.0      53.000000
Ghana                       0.979199 -1.019578  1.0      37.000000
Iran                        0.640642 -1.152297  1.0      31.666667
Japan                       1.377855 -0.948495  1.0      30.250000
Korea Republic              0.840338 -1.449814  1.0      42.250000
Mexico                      0.589590 -1.154613  1.0      46.666667
Morocco                     1.006855 -1.718366  1.0      34.285714
Netherlands                 1.128588 -1.222637  1.0      44.000000
Poland                      0.626272 -1.493418  1.0      32.000000
Portugal                    1.655185 -0.796941  1.0      53.800000
Qatar                       1.115767 -0.815368  1.0      39.333333
Saudi Arabia                0.976238 -1.022179  1.0      36.666667
Senegal                     1.343085 -1.077420  1.0      38.500000
Serbia                      1.066614 -0.916387  1.0      42.666667
Spain                       1.193911 -0.905726  1.0      67.000000
Switzerland                 1.024097 -1.300880  1.0      43.000000
Tunisia                     0.805353 -1.119304  1.0      38.666667
United States               0.767335 -1.435367  1.0      47.000000
Uruguay                     1.149932 -0.665750  1.0      41.000000
Wales                       0.867461 -1.093756  1.0      41.000000

In [62]:
ipl=pd.read_csv('deliveries.csv')
ipl

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179073,11415,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,SR Watson,SL Malinga,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179074,11415,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179075,11415,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,1,0,1,SR Watson,run out,KH Pandya
179076,11415,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179077,11415,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,0,0,0,SN Thakur,lbw,NaN

Q-5: Find batsman in below category-
1- Highest score while chasing

In [ ]:

chassing_df=ipl[ipl['inning']==2]
batsman_inning=chassing_df.groupby(['match_id','batsman'])
batsman_inning['batsman_runs'].sum().sort_values(ascending=False).head(1)

match_id  batsman
7953      SR Watson    121
Name: batsman_runs, dtype: int64

2- Best Strike rate while chasing and have faced 100+ balls

In [110]:
def best_strike_rate(group):
    balls_faced=group['ball'].size

    if balls_faced<100:
        return np.nan
    
    total_score=group['batsman_runs'].sum()

    return (total_score/balls_faced)*100

batsman_group=chassing_df.groupby('batsman')
batsman_group.apply(best_strike_rate).dropna().sort_values(ascending=False).head(1)

batsman
SP Narine    171.088435
dtype: float64

Q-6 Most Successful bowler against any batsman. Find that pair of bowler and batsman.
Most Successful in terms of dissmissal. A bowler who have dissmissed any batsman most no of times. If any two pairs have same no of dissmisal, consider runs conceded by bowler to that batsman. Those who have concede lesser runs is more successful.

In [121]:

bowler_wickets = ['caught', 'bowled', 'lbw', 'stumped', 'caught and bowled']


dismissals_df = ipl[(ipl['player_dismissed'] == ipl['batsman']) & 
                    (ipl['dismissal_kind'].isin(bowler_wickets))]


true_wickets = dismissals_df.groupby(['bowler', 'batsman']).size().reset_index(name='true_dismissals')

runs_conceded = ipl.groupby(['bowler', 'batsman'])['batsman_runs'].sum().reset_index()


final_comparison = pd.merge(true_wickets, runs_conceded, on=['bowler', 'batsman'])


winner_pair = final_comparison.sort_values(
    by=['true_dismissals', 'batsman_runs'], 
    ascending=[False, True]
).head(1)

print(winner_pair)

      bowler   batsman  true_dismissals  batsman_runs
6431  Z Khan  MS Dhoni                7            74

Q-7: Most successful batting pair in IPL. Batting pair who have scored most runs playing together.

In [183]:
ipl[['Player_1','Player_2']]=np.sort(ipl[['batsman','non_striker']],axis=1)
ipl.groupby(['Player_1','Player_2'])['total_runs'].sum().reset_index().sort_values(by='total_runs',ascending=False).head(1)

           Player_1 Player_2  total_runs
277  AB de Villiers  V Kohli        2860

Q-8: Make a dataframe for all batting pairs played together.
Batsman1 Batsman2 Runs Avg StrikeRate
Just to ease this question you can count wide-balls for strike rate.

In [187]:
new_df=ipl.groupby(['Player_1','Player_2']).agg(
    Runs= ('total_runs','sum'),
    Avg= ('total_runs','mean'),
   
).reset_index()

new_df['StrikeRate']=new_df['Avg']*100
new_df.sort_values(by='Runs',ascending=False,inplace=True)
new_df.rename(columns={'Player_1':'Batsman1','Player_2':'Batsman2'},inplace=True)
new_df

            Batsman1      Batsman2  Runs       Avg  StrikeRate
277   AB de Villiers       V Kohli  2860  1.535983  153.598281
1075        CH Gayle       V Kohli  2802  1.420172  142.017233
1265       DA Warner      S Dhawan  2357  1.366377  136.637681
1624       G Gambhir    RV Uthappa  1906  1.337544  133.754386
2775        MS Dhoni      SK Raina  1464  1.387678  138.767773
...              ...           ...   ...       ...         ...
719     Ankit Sharma   Rashid Khan     0  0.000000    0.000000
721     Ankit Sharma  TP Sudhindra     0  0.000000    0.000000
2600        MA Starc     S Aravind     0  0.000000    0.000000
18        A Chandila       OA Shah     0  0.000000    0.000000
26       A Choudhary      S Badree     0  0.000000    0.000000

[3430 rows x 5 columns]